### ISSUE TITLE
Namespace: use the proper namespace when calling with-designators

### ISSUE THREAD

**Issue by mpomarlan** [cram-code/cram_tutorials#4]
Add mention of the cram-language-designator-support package at 

https://github.com/cram-code/cram_tutorials/blob/master/cram_beginner_tutorial/src/tutorial.lisp#L170

to prevent with-designator from being treated as an undefined symbol. (Alternatively, add a uses line in package.lisp)

**Comment by gaya-** [comment]
@mpomarlan is this still an issue? I grepped for `with-designators` in beginner tutorials and the only instance had the proper namespace in front.
